### ISSUE TITLE
No terminal selection background for Atelier_SulphurpoolLight and others

### ISSUE THREAD

**Issue by freref** [atelierbram/Atelier-VSCode-Themes#1]
Currently Atelier_SulphurpoolLight and some other Atelier themes don't have a terminal selection background.

Workaround is adding the following with you desired colour to your user settings:
```
    "workbench.colorCustomizations": {
        "terminal.selectionBackground": "#528BFF66"
    },
```

**Comment by atelierbram** [comment]
Ok, I see what you mean. None of my themes currently have a setting for `terminal.selectionBackground`, and now there's also highlighting for `find` in the integrated terminal it seems ... which is all very cool. Whenever I have some time I will work on this, but don't hold your breath 😉 .

https://stackoverflow.com/questions/68776940/vscode-terminal-change-the-find-highlight-color?noredirect=1&lq=1
https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_66.md#display-all-find-matches

**Comment by freref** [comment]
I'm good with my workaround, just wanted to let you know. Thanks for taking a look!

**Comment by atelierbram** [comment]
@freref should be fixed now, added some semi-transparency too. Please let me know if this update works for you or not.
