### ISSUE TITLE
Problem peek view gets dark background in the light themes

### ISSUE THREAD

**Issue by danmichaelo** [atelierbram/Atelier-VSCode-Themes#2]
The "problem peek view" gets a dark background color in the Atelier light themes, making the text unreadable:
 
![image](https://github.com/atelierbram/Atelier-VSCode-Themes/assets/434495/a455406e-95e9-42af-8439-f193eda8f5b6)

As a workaround, I configured `editorMarkerNavigation.background` directly in my `settings.json`:

```json
"workbench.colorCustomizations": {
  "[Atelier_SeasideLight]": {
    "editorMarkerNavigation.background": "#F4FBF4"
  }
}
```

**Comment by atelierbram** [comment]
@danmichaelo Thanks for the heads up. Should be fixed now, but please let me know if this update works for you or not.
